[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pydog"
version = "0.1.0"
description = "Dog in Python"
authors = [{ name="you" }]
dependencies = []
